### PR TITLE
Update worker.py to work with latest version of python-rq

### PR DESCRIPTION
**Pull request by davidmurray**
Thanks !

### CODE REVIEW

**Comment by michaelbrooks** [comment]
Does this maintain compatibility with older rq-win versions? Can you add a note to the readme explaining what versions of rq-win you think this library should work with after this change?

**Comment by davidmurray** [comment]
> Does this maintain compatibility with older rq-win versions? Can you add a note to the readme explaining what versions of rq-win you think this library should work with after this change?

Do you mean versions of Python RQ?

**Comment by michaelbrooks** [comment]
Ha, yes. Sorry, it's been a while since I worked on this.

**Comment by davidmurray** [comment]
@michaelbrooks  Done! :)

**Pull request merged**
